/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.lojavendas.view;

import javax.swing.JDesktopPane;

/**
 *
 * @author Michel
 */
public class PrincipalView extends javax.swing.JFrame {

    JDesktopPane desktop = new JDesktopPane();

    public PrincipalView() {
        initComponents();
        //this.setExtendedState(MAXIMIZED_BOTH);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        JMICategoriaProduto = new javax.swing.JMenuItem();
        JMICliente = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        JMIVenda = new javax.swing.JMenuItem();
        JMIUsuario = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Loja de Vendas");

        jMenu1.setText("Cadastrar");

        JMICategoriaProduto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        JMICategoriaProduto.setText("Categoria/Produto");
        JMICategoriaProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMICategoriaProdutoActionPerformed(evt);
            }
        });
        jMenu1.add(JMICategoriaProduto);

        JMICliente.setText("Cliente");
        JMICliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMIClienteActionPerformed(evt);
            }
        });
        jMenu1.add(JMICliente);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Serviço");

        JMIVenda.setText("Venda");
        JMIVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMIVendaActionPerformed(evt);
            }
        });
        jMenu2.add(JMIVenda);

        JMIUsuario.setText("Usuário");
        JMIUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMIUsuarioActionPerformed(evt);
            }
        });
        jMenu2.add(JMIUsuario);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1264, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 586, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JMICategoriaProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMICategoriaProdutoActionPerformed
        setContentPane(desktop);
        CategoriaProdutoView cpv = new CategoriaProdutoView(JMICategoriaProduto);
      
        cpv.setVisible(true);
        desktop.add(cpv);
        JMICategoriaProduto.setEnabled(false);
    }//GEN-LAST:event_JMICategoriaProdutoActionPerformed

    private void JMIClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMIClienteActionPerformed
        setContentPane(desktop);
        ClienteView cv = new ClienteView(JMICliente);
        
        cv.setVisible(true);
        desktop.add(cv);
        JMICliente.setEnabled(false);
    }//GEN-LAST:event_JMIClienteActionPerformed

    private void JMIVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMIVendaActionPerformed
        setContentPane(desktop);
        VendaView cv = new VendaView(JMIVenda);
        
        cv.setVisible(true);
        desktop.add(cv);
        JMIVenda.setEnabled(false);
    }//GEN-LAST:event_JMIVendaActionPerformed

    private void JMIUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMIUsuarioActionPerformed
        setContentPane(desktop);
        UsuarioView cv = new UsuarioView(JMIUsuario);
        
        cv.setVisible(true);
        desktop.add(cv);
        JMIUsuario.setEnabled(false);
    }//GEN-LAST:event_JMIUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem JMICategoriaProduto;
    private javax.swing.JMenuItem JMICliente;
    private javax.swing.JMenuItem JMIUsuario;
    private javax.swing.JMenuItem JMIVenda;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
