/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.lojavendas.view;

import com.mycompany.lojavendas.controller.TipoUsuarioController;
import com.mycompany.lojavendas.controller.UsuarioController;
import com.mycompany.lojavendas.model.TipoUsuario;
import com.mycompany.lojavendas.model.Usuario;
import com.mycompany.lojavendas.tools.JanelaMensagem;
import com.mycompany.lojavendas.tools.TableCellRendererColor;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.JMenuItem;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Michel
 */
public class UsuarioView extends javax.swing.JInternalFrame {

    JMenuItem menuUsuario;

    public UsuarioView(JMenuItem menuUsuario) {
        initComponents();
        this.menuUsuario = menuUsuario;
        BGAtivoInativo.add(JCBAtivo);
        BGAtivoInativo.add(JCBInativo);

        carregarListaTipoUsuario();

        JTable.getTableHeader().setReorderingAllowed(false);
        JTable.setAutoCreateRowSorter(true);
        JTable.setDefaultRenderer(Object.class, new TableCellRendererColor());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BGAtivoInativo = new javax.swing.ButtonGroup();
        JTFLogin = new javax.swing.JTextField();
        JPFSenha = new javax.swing.JPasswordField();
        JCTipoUsuario = new javax.swing.JComboBox<>();
        JCBAtivo = new javax.swing.JCheckBox();
        JCBInativo = new javax.swing.JCheckBox();
        JBSalvar = new javax.swing.JButton();
        JBBuscar = new javax.swing.JButton();
        JTFPesquisa = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTable = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Usuário");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        JTFLogin.setNextFocusableComponent(JPFSenha);

        JCBAtivo.setText("Ativo");

        JCBInativo.setText("Inativo");

        JBSalvar.setText("Salvar");
        JBSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBSalvarActionPerformed(evt);
            }
        });

        JBBuscar.setText("Buscar");
        JBBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBBuscarActionPerformed(evt);
            }
        });

        JTFPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JTFPesquisaKeyPressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Login");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Senha");

        JTable.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        JTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Login", "Tipo Usuário", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(JTable);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Tipo de Usuário");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JPFSenha, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JTFLogin, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(JBSalvar)
                    .addComponent(jLabel5)
                    .addComponent(JCTipoUsuario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JCBAtivo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addComponent(JCBInativo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JBBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JTFPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JTFPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JBBuscar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JTFLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JPFSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JCTipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JCBAtivo)
                            .addComponent(JCBInativo))
                        .addGap(21, 21, 21)
                        .addComponent(JBSalvar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        menuUsuario.setEnabled(true);
    }//GEN-LAST:event_formInternalFrameClosing

    private void JBSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBSalvarActionPerformed
        String login = JTFLogin.getText();
        String senha = new String(JPFSenha.getPassword());
        String tipoUsuario = JCTipoUsuario.getSelectedItem().toString();

        Usuario u = new Usuario();
        u.setLogin(login);
        u.setSenha(senha);

        UsuarioController uc = new UsuarioController();
        uc.salvar(u, tipoUsuario);
    }//GEN-LAST:event_JBSalvarActionPerformed

    private void JBBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBBuscarActionPerformed
        String busca = JTFPesquisa.getText();
        TipoUsuarioController tuc = new TipoUsuarioController();
        List<TipoUsuario> lista = tuc.listaDeUsuarios(busca);
        carregarTabela(lista);
    }//GEN-LAST:event_JBBuscarActionPerformed

    private void JTFPesquisaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTFPesquisaKeyPressed
       if(evt.getKeyCode() == KeyEvent.VK_ENTER){
           JBBuscarActionPerformed(null);
       }
    }//GEN-LAST:event_JTFPesquisaKeyPressed

    private void carregarTabela(List<TipoUsuario> lista) {
        DefaultTableModel modelo = (DefaultTableModel) JTable.getModel();
        JTable.getColumnModel().getColumn(0).setMinWidth(0);
        JTable.getColumnModel().getColumn(0).setMaxWidth(0);
        modelo.setRowCount(0);

        if (lista.isEmpty()) {
            JanelaMensagem.nadaNaLista();
        } else {
            for (int i = 0; i < lista.size(); i++) {
                String status;
                if (lista.get(i).getUsuario().isStatus() == true) {
                    status = "Ativo";
                } else {
                    status = "Inativo";
                }

                modelo.addRow(new Object[]{
                    lista.get(i).getUsuario().getId(),
                    lista.get(i).getUsuario().getLogin(),
                    lista.get(i).getNome(),
                    status
                });
            }
        }
    }

    private void carregarListaTipoUsuario() {
        TipoUsuarioController tuc = new TipoUsuarioController();
        List<String> lista = tuc.listaTipoUsuario();

        lista.forEach((s) -> {
            JCTipoUsuario.addItem(s);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BGAtivoInativo;
    private javax.swing.JButton JBBuscar;
    private javax.swing.JButton JBSalvar;
    private javax.swing.JCheckBox JCBAtivo;
    private javax.swing.JCheckBox JCBInativo;
    private javax.swing.JComboBox<String> JCTipoUsuario;
    private javax.swing.JPasswordField JPFSenha;
    private javax.swing.JTextField JTFLogin;
    private javax.swing.JTextField JTFPesquisa;
    private javax.swing.JTable JTable;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
